#!/bin/sh
echo "${#1}" | awk 'BEGIN{printf " "}{for(i=0;i<$1+2;i++){printf "%s", "-"}}END{printf "\n"}'
echo "< $1 >"
echo "${#1}" | awk 'BEGIN{printf " "}{for(i=0;i<$1+2;i++){printf "%s", "-"}}END{printf "\n"}'
echo "   \\"
echo "     🐍"

