#!/bin/sh
a="$@"
echo "${#a}" | awk 'BEGIN{printf " "}{for(i=0;i<$1+2;i++){printf "%s", "-"}}END{printf "\n"}'
echo "< $a >"
echo "${#a}" | awk 'BEGIN{printf " "}{for(i=0;i<$1+2;i++){printf "%s", "-"}}END{printf "\n"}'
echo "   \\"
echo "     🐍"

